version: '3'
services:
  # website
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile # Dockerfile path
    ports:
      - "${WEB_PORT:-8080}:8080"  # Use the WEB_PORT environment variable or default to 8080
    depends_on:
      - mongodb
      # - redis
      - postgres
      # - neo4j
      # - elasticsearch
    restart: always
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - ./src:/app  # Mount the current directory to /app in the container

  # db
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./data/mongodb:/data/mongodb

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - ./data/redis:/data/redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data/postgres:/data/postgres

  # neo4j:
  #   image: neo4j:latest
  #   ports:
  #     - "${NEO4J_PORT:-7687}:7687"
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  #   volumes:
  #     - ./data/neo4j:/data/neo4j

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "${ELASTICSEARCH_PORT:-9200}:9200"
  #   volumes:
  #     - ./data/elasticsearch:/data/elasticsearch